/*CMD
  command: /Adminlogin
  help: 
  need_reply: 
  auto_retry_time: 
  folder: 

  <<ANSWER
Welcome Admin 🔱

Here You Can Do The Following :
• Broadcast News ✅
• Check A User's Balance ✅
• Test Payment ✅
• Remove Balance From A User ✅
• Get Funds For Bonus Give Aways ✅
• Send Balance to A User ✅
• If You Want to Check The User's Conversation With the Bot Download BGram And Login As A Bot ✅
• Blocking A User (Soon) 
• Test Admin Panel Security ✅

  ANSWER
  keyboard: Broadcast 📣 , User Settings 👥,\nGet Funds 💰, Test 🧾 ,\nTest Security 🔒,\nBack 🔙   
  aliases: back 🔙
CMD*/

/*CMD
  command: Admin
  help: 
  need_reply: 
  auto_retry_time: 
  folder: 

  <<ANSWER
Welcome Admin 🔱

Here You Can Do The Following :
• Broadcast News ✅
• Check A User's Balance ✅
• Test Payment ✅
• Remove Balance From A User ✅
• Get Funds For Bonus Give Aways ✅
• Send Balance to A User ✅
• If You Want to Check The User's Conversation With the Bot Download BGram And Login As A Bot ✅
• Blocking A User (Soon) 
• Test Admin Panel Security ✅

  ANSWER
  keyboard: Broadcast 📣 , User Settings 👥,\nGet Funds 💰, Test 🧾 ,\nTest Security 🔒,\nBack 🔙
  aliases: back to panel
CMD*/


